apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: resqzuc2h-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: resqzuc2h-python 
  name: resqzuc2h-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: resqzuc2h-python 
