apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: resqzuc2h-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:035da7e8df399a452e5a37732ec4d74ed18e4b9e@sha256:b52ea2d5bddb0034416ecdd0c8d120458abebcbde722ec37d5bfc83c76596d03
          name: container-image
